# omninmo Configuration File

# NOTICE: This configuration file has been refactored into multiple files in the 'config' directory.
# This file remains for backward compatibility but is no longer the primary configuration source.
# Please use the files in the 'config' directory for all future configuration changes:
#
# - config/model.yaml     # ML model parameters
# - config/features.yaml  # Feature engineering parameters
# - config/app.yaml       # App settings (watchlist, cache)
# - config/data.yaml      # API access and data settings
#
# For full details on the refactoring, see docs/devplan/2025-03-17-config-refactoring-plan.md

# This file will be automatically loaded if the config directory structure is not found.
