# omninmo Configuration File

# Model Configuration
model:
  xgboost:
    learning_rate: 0.1
    max_depth: 6
    n_estimators: 100
    random_state: 42
    test_size: 0.2
  normalization:
    method: "sigmoid"  # Options: sigmoid, linear, tanh
    sigmoid_k: 10      # Scaling factor for sigmoid
    linear_min: -0.1   # -10% maps to 0 (for linear method)
    linear_max: 0.1    # +10% maps to 1 (for linear method)
  training:
    # Number of days to look ahead for prediction (updated for medium-term)
    forward_days: 90
    # Historical data period for training (increased for better medium-term patterns)
    period: "10y"
    # Data interval (1d recommended for best results)
    interval: "1d"
    # Minimum number of days required for reliable predictions
    min_data_days: 60  # Minimum days of data required for training
    min_feature_days: 30  # Minimum days required after feature generation
    # Score thresholds for mapping to categorical ratings (adjusted for 90-day horizon)
    score_thresholds:
      strong_buy: 0.8   # Scores >= 0.8 are Strong Buy
      buy: 0.6          # Scores >= 0.6 are Buy
      hold: 0.4         # Scores >= 0.4 are Hold
      sell: 0.2         # Scores >= 0.2 are Sell
      strong_sell: 0.0  # Scores < 0.2 are Strong Sell
    # Return thresholds for rating categories (adjusted for 90-day horizon)
    rating_thresholds:
      strong_buy: 0.15   # >15% return
      buy: 0.08         # >8% return
      hold: -0.08       # -8% to 8% return
      sell: -0.15       # <-15% return
      strong_sell: -0.15 # <-15% return
    # Default tickers for training (diverse set of stocks)
    default_tickers:
      - AAPL    # Apple Inc. - Consumer electronics and software
      - AMAT    # Applied Materials - Semiconductor equipment and materials
      - AMD     # Advanced Micro Devices - Semiconductor manufacturing
      - AMRN    # Amarin Corporation - Biopharmaceutical (small-cap)
      - AMZN    # Amazon.com - E-commerce and cloud computing
      - ANET    # Arista Networks - Cloud networking solutions
      - APP     # AppLovin - Mobile app technology and marketing
      - BABA    # Alibaba Group - Chinese e-commerce and technology
      - BAC     # Bank of America - Banking and financial services
      - BE      # Bloom Energy - Clean energy technology (struggling)
      - BLBD    # Blue Bird Corp - School bus manufacturer (small-cap)
      - BYND    # Beyond Meat - Plant-based meat products (struggling)
      - CALM    # Cal-Maine Foods - Egg production and distribution (small-cap)
      - CAT     # Caterpillar Inc. - Heavy equipment manufacturing
      - CHEF    # The Chefs' Warehouse - Food distribution (mid-cap)
      - CRM     # Salesforce - Cloud-based software
      - CUBI    # Customers Bancorp - Regional bank (small-cap)
      - CVX     # Chevron Corporation - Integrated oil and gas
      - CWEN    # Clearway Energy - Renewable energy (mid-cap)
      - DIS     # The Walt Disney Company - Entertainment and media
      - DUK     # Duke Energy - Electric power holding company
      - ELLO    # Ellomay Capital - Renewable energy (small-cap)
      - GEVO    # Gevo Inc. - Renewable chemicals and biofuels (struggling)
      - GOOGL   # Alphabet Inc. - Internet services and technology
      - GS      # Goldman Sachs - Investment banking and securities
      - HOLX    # Hologic - Medical devices and diagnostics (mid-cap)
      - HON     # Honeywell International - Industrial conglomerate
      - IBM     # International Business Machines - Technology services and consulting
      - INTC    # Intel Corporation - Semiconductor manufacturing
      - IONQ    # IonQ - Quantum computing technology
      - JNJ     # Johnson & Johnson - Healthcare and pharmaceuticals
      - JPM     # JPMorgan Chase - Banking and financial services
      - KO      # The Coca-Cola Company - Beverage manufacturing
      - LMT     # Lockheed Martin - Aerospace and defense
      - LRCX    # LRCX - Semiconductor equipment and materials
      - META    # Meta Platforms - Social media and technology
      - MPC     # Marathon Petroleum - Oil refining and marketing (mid-cap)
      - MSFT    # Microsoft Corporation - Software and cloud computing
      - NEE     # NextEra Energy - Renewable energy and utilities
      - NFLX    # Netflix - Streaming media and entertainment
      - NVDA    # NVIDIA Corporation - Graphics and AI computing
      - PFE     # Pfizer - Pharmaceutical manufacturing
      - PG      # Procter & Gamble - Consumer goods
      - PLTR    # Palantir Technologies - Data analytics software
      - SNOW    # Snowflake - Cloud data platform
      - SOFI    # SoFi Technologies - Digital financial services (struggling)
      - TALO    # Talos Energy - Oil and gas exploration (small-cap)
      - TDOC    # Teladoc Health - Telemedicine services (struggling)
      - TSLA    # Tesla - Electric vehicles and clean energy
      - V       # Visa Inc. - Global payments technology
      - VIRT    # Virtu Financial - Market making and trading (mid-cap)
      - WDAY    # Workday - Enterprise cloud applications
      - WKHS    # Workhorse Group - Electric delivery vehicles (struggling)
      - XOM     # Exxon Mobil - Integrated oil and gas
      - XPO     # XPO Logistics - Transportation and logistics (mid-cap)

# Rating Configuration
rating:
  map:
    0: "Strong Sell"
    1: "Sell"
    2: "Hold"
    3: "Buy"
    4: "Strong Buy"
  colors:
    strong_buy: "#1E8449"  # Dark Green
    buy: "#82E0AA"        # Light Green
    hold: "#F4D03F"       # Yellow
    sell: "#F5B041"       # Orange
    strong_sell: "#C0392B" # Red

# App Configuration
app:
  title: "omninmo - Stock Prediction"
  icon: "📈"
  layout: "wide"
  initial_sidebar_state: "expanded"
  cache:
    ttl: 86400  # Cache time to live in seconds
  watchlist:
    default:
      - AI     # AI Software
      - AMAT   # Semiconductor Manufacturing
      # - AMZN   # E-commerce / Cloud
      # - ANET   # Cloud Networking
      # - AAPL   # Consumer Tech
      # - APP    # Mobile Tech / Marketing
      # - AXP    # Financial Services
      # - BABA   # Chinese E-commerce
      # - BKNG   # Travel / Online Booking
      # - CRM    # Enterprise CRM
      # - CRWD   # Cybersecurity
      # - FTNT   # Network Security
      - GOOGL  # Big Tech / AI
      - HPE    # Enterprise IT
      - IONQ   # Quantum Computing
      - LRCX   # Semiconductor Equipment
      - LULU   # Retail / Athleisure
      - MELI   # Latin American E-commerce
      - META   # Social Media / Metaverse
      - NVDA   # Semiconductors / AI
      - PANW   # Cybersecurity
      - PDD    # Chinese E-commerce
      - PLTR   # Data Analytics / AI
      # - QCOM   # Mobile Technology
      # - QQQ    # Nasdaq 100 ETF
      # - SNOW   # Data Cloud Platform
      # - SPY    # S&P 500 ETF
      # - UBER   # Mobility / Delivery
      # - V      # Payments
      # - WDAY   # Enterprise Software
      # - ZS     # Cloud Security
  parallel_processing:
    max_workers: 5

# Data Configuration
data:
  fmp:
    api_key: ${FMP_API_KEY}  # Will be loaded from environment variable
    cache_dir: "cache"
  max_age_days: 30  # Maximum age of data before requiring refresh
  sample_data:
    default_prices:
      # Original tech stocks
      AAPL: 175.0
      MSFT: 380.0
      AMZN: 180.0
      GOOGL: 150.0
      META: 480.0
      TSLA: 180.0
      NVDA: 800.0
      JPM: 190.0
      V: 280.0
      JNJ: 150.0
      WMT: 60.0
      PG: 160.0
      DIS: 110.0
      NFLX: 600.0
      INTC: 40.0
      # Energy Sector
      XOM: 105.0
      CVX: 155.0
      MPC: 145.0
      TALO: 12.0
      GEVO: 1.2
      # Healthcare Sector
      PFE: 28.0
      HOLX: 75.0
      AMRN: 1.0
      TDOC: 15.0
      # Financials Sector
      BAC: 35.0
      GS: 385.0
      VIRT: 20.0
      CUBI: 25.0
      SOFI: 8.0
      # Industrial Sector
      CAT: 270.0
      HON: 200.0
      XPO: 120.0
      BLBD: 20.0
      WKHS: 0.5
      # Consumer Staples Sector
      KO: 60.0
      CHEF: 40.0
      CALM: 45.0
      BYND: 10.0
      # Utilities/Energy Sector
      NEE: 60.0
      DUK: 95.0
      CWEN: 30.0
      ELLO: 8.0
      BE: 4.0
    default_volatility:
      # Original tech stocks
      AAPL: 0.015
      MSFT: 0.018
      AMZN: 0.022
      GOOGL: 0.020
      META: 0.025
      TSLA: 0.035
      NVDA: 0.030
      JPM: 0.015
      V: 0.012
      JNJ: 0.010
      WMT: 0.008
      PG: 0.007
      DIS: 0.018
      NFLX: 0.028
      INTC: 0.020
      # Energy Sector
      XOM: 0.015
      CVX: 0.015
      MPC: 0.020
      TALO: 0.035
      GEVO: 0.050
      # Healthcare Sector
      PFE: 0.012
      HOLX: 0.018
      AMRN: 0.045
      TDOC: 0.040
      # Financials Sector
      BAC: 0.018
      GS: 0.020
      VIRT: 0.025
      CUBI: 0.035
      SOFI: 0.045
      # Industrial Sector
      CAT: 0.018
      HON: 0.015
      XPO: 0.025
      BLBD: 0.035
      WKHS: 0.055
      # Consumer Staples Sector
      KO: 0.010
      CHEF: 0.025
      CALM: 0.030
      BYND: 0.045
      # Utilities/Energy Sector
      NEE: 0.015
      DUK: 0.012
      CWEN: 0.025
      ELLO: 0.035
      BE: 0.045

# Logging Configuration
logging:
  level: DEBUG
  file:
    max_bytes: 10485760  # 10MB
    backup_count: 5
    directory: "logs"
  handlers:
    trainer: "trainer.log"
    feature_engineer: "feature_engineer.log"
    xgboost_predictor: "xgboost_predictor.log"
    fmp_data_fetcher: "fmp_data_fetcher.log"

# Chart Configuration
charts:
  candlestick:
    height: 600
    template: "plotly_white"
  technical:
    moving_averages:
      - 50
      - 200
    colors:
      ma_50: "orange"
      ma_200: "red"
      volume: "rgba(0, 0, 255, 0.5)"

# Feature Configuration
features:
  thresholds:
    rsi: 30  # RSI oversold/overbought threshold
    stochastic:
      low: 30  # Stochastic oversold threshold
      high: 70  # Stochastic overbought threshold
    volume_increase: 25  # Volume increase threshold (percentage)
    trend_strength: 25  # ADX trend strength threshold
  min_rolling_periods: 30  # Minimum periods for rolling calculations
