version: '3.8'

services:
  folio:
    build: .
    ports:
      - "8050:8050"
    environment:
      - PORT=8050
      - PYTHONPATH=/app
      - DATA_SOURCE=yfinance
    volumes:
      - ./config:/app/config
      - ./data:/app/data
      - ./.env:/app/.env
    restart: unless-stopped
