[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_optional = true
plugins = ["numpy.typing.mypy_plugin"]

[[tool.mypy.overrides]]
module = "dash.*"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "pandas.*"
ignore_missing_imports = true

[tool.ruff]
# Line length and target version are top-level
line-length = 88
target-version = "py311"

[tool.ruff.lint]
# Enable recommended rules + specific ones useful for data science projects
select = [
    "E",   # pycodestyle errors
    "F",   # pyflakes
    "I",   # isort
    "N",   # pep8-naming
    "UP",  # pyupgrade
    "PL",  # pylint
    "RUF", # ruff-specific rules
    "W",   # pycodestyle warnings
]

# Ignore specific rules
ignore = [
    "E501",  # line too long - let's handle line length more flexibly for data science code
    "N803",  # argument name should be lowercase - common in ML to use X, y
    "N806",  # variable name should be lowercase - common in ML to use X_train, y_test
    "PLR0913",  # too many arguments - common in ML functions with many parameters
    "PLR0912",  # too many branches - common in ML data processing and training loops
    "PLR0915",  # too many statements - common in ML training and evaluation functions
    "PLR2004",  # magic value used in comparison - common in data processing code
]

# Allow autofix for all enabled rules (when `--fix`) is provided
fixable = ["ALL"]

# Exclude a variety of commonly ignored directories
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "build",
    "dist",
    "mlruns",
    ".pytest_cache",
    ".archive",
]

# Allow unused variables when underscore-prefixed
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.lint.per-file-ignores]
# DO NOT IGNORE UNLESS IT'S A REALLY GOOD REASON!
"__init__.py" = ["F401"]  # Re-exports are common in __init__.py files

[tool.ruff.lint.isort]
known-first-party = ["src"]
